### ISSUE TITLE
[BUG] Issues link in vscode extension list 404

### ISSUE THREAD

**Issue by tyeth** [wmerkens/vscode-circuitpython#14]
The Issues link is broken. Takes you to merkens instead of wmerkens.
i.e. https://github.com/merkens/vscode-circuitpython/issues
![Screenshot 2024-12-14 at 16 08 15](https://github.com/user-attachments/assets/a57cd112-f457-435e-af8e-119da79f1c3f)

**Comment by wmerkens** [comment]
Ok, I will fix it on the next version.
