### ISSUE TITLE
[BUG] Stubs seem to not load for "board"

### ISSUE THREAD

**Issue by FrozenGalaxy** [wmerkens/vscode-circuitpython#15]
**Describe the bug**
Stubs seem to not load for "board"

I'm on Windows and have a basic code.py setup on a qtpy.
I can see it adds the extra path's but that doesn't seem to help

```
data\extensions\wmerkens.vscode-circuitpython-v2-0.2.8\stubs
data\extensions\wmerkens.vscode-circuitpython-v2-0.2.8\boards\0x239A\0x8112
data\user-data\User\globalStorage\wmerkens.vscode-circuitpython-v2\bundle\20241214\adafruit-circuitpython-bundle-py-20241214\lib
```
as it pulls the info from:
`data\extensions\wmerkens.vscode-circuitpython-v2-0.2.8\stubs\board\__init__.pyi`

any idea why?

**Comment by wmerkens** [comment]
When you started up VSC and opened the CIRCUITPY drive, what Bundle did it claim to download and install.

Usually, it is daily, so if you opened VSC today, it would be 20241216.

Check the file in the CIRCUITPY drive in .vscode/settings.json for this line.

data\user-data\User\globalStorage\wmerkens.vscode-circuitpython-v2\bundle\20241214\adafruit-circuitpython-bundle-py-20241214\lib

If it's still 20241214, it should be changed to 20241216.

I am aware of a bug in the library manager that causes this not to update, and this file is not being updated properly.

**Comment by FrozenGalaxy** [comment]
I just restarted it and it downloads 17. So that part is right, but it still only loads the default "Board" stub
instead of `data\extensions\wmerkens.vscode-circuitpython-v2-0.2.8\boards\0x239A\0x8112`
![image](https://github.com/user-attachments/assets/7deeb683-7cb7-48b6-b470-a1942fd091ca)

![image](https://github.com/user-attachments/assets/e8d0e73f-b14b-4c15-abd0-a0e01f12aee2)

**Comment by wmerkens** [comment]
I will look into this when I finish fixing the Library Manager code.

**Comment by wmerkens** [comment]
Ok, I fixed the issue which was in the board generator script, it was not naming the pyi files properly. 
new version 0.3.1
